name: Chromatic

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

env:
  CI: true

concurrency:
  group: chromatic-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TURBO_TELEMETRY_DISABLED: '1'

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          # Refer to: https://www.chromatic.com/docs/github-actions/#recommended-configuration-for-build-events.
          ref: ${{ github.event.pull_request.head.ref }}
        env:
          # Refer to: https://www.chromatic.com/docs/github-actions/#recommended-configuration-for-build-events.
          CHROMATIC_BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
          CHROMATIC_SHA: ${{ github.event.pull_request.head.sha || github.ref }}
          CHROMATIC_SLUG: ${{ github.repository }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '>=24.0.0'
          check-latest: true
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Restore Turborepo cache
        id: cache-turborepo-restore
        uses: actions/cache/restore@v5
        with:
          key: ${{ runner.os }}-turbo-chromatic-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-chromatic-
            ${{ runner.os }}-turbo-
          path: .turbo

      - name: Get base SHA
        id: get-base-sha
        shell: bash
        # For PRs, it's the base SHA of the PR.
        # For pushes to main, the base SHA is the before SHA of the push event.
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "VALUE=${{ github.event.pull_request.base.sha }}" >> "$GITHUB_OUTPUT"
          else
            echo "VALUE=${{ github.event.before }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Get is draft
        id: get-is-draft
        # For PRs, check if the PR is a draft.
        # For pushes to main, it's always false.
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "VALUE=${{ github.event.pull_request.draft }}" >> "$GITHUB_OUTPUT"
          else
            echo "VALUE=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Get affected Storybooks
        id: affected
        working-directory: ${{ github.workspace }}
        run: pnpm tsx tooling/getAffectedStorybooks.ts
        env:
          BASE_SHA: ${{ steps.get-base-sha.outputs.VALUE }}

      - name: Chromatic - Home
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.HOME_CHROMATIC_PROJECT_TOKEN }}
          workingDir: apps/home/storybook
          onlyChanged: true
          exitOnceUploaded: true
          autoAcceptChanges: main
          skip: ${{ steps.affected.outputs['@apps/home-storybook'] == 'false' || steps.get-is-draft.outputs.VALUE == 'true' }}
          debug: true

      - name: Chromatic - Packages
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.PACKAGES_CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/storybook
          onlyChanged: true
          exitOnceUploaded: true
          autoAcceptChanges: main
          skip: ${{ steps.affected.outputs['@apps/packages-storybook'] == 'false' || steps.get-is-draft.outputs.VALUE == 'true' }}
          debug: true

      - name: Save Turborepo cache
        id: cache-turborepo-save
        if: always() && steps.cache-turborepo-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          key: ${{ steps.cache-turborepo-restore.outputs.cache-primary-key }}
          path: .turbo
